### ISSUE TITLE
[Bug/建议] 添加一个权重正反序开关

### ISSUE THREAD

**Issue by zhangnelson** [CarmJos/UserPrefix#12]
### **功能简述**
添加一个自定义权重正序或者反序的功能

### **需求来源**
也算是一个Bug吧，在TAB中，权重越大，称号越排下边，自定义正反序可以解决使用者的需求

### **功能参考**(可选)
暂无

### **附加内容**
暂无

**Comment by CarmJos** [comment]
您好，相关问题已定位。请下载 [runs@1903490405](https://github.com/CarmJos/UserPrefix/actions/runs/1903490405) 中的构建并安装，帮助我进行测试，谢谢！

**Comment by zhangnelson** [comment]
> 

第一次测试  **order-desc为true时** ，A前缀的权重为99 ，upa reload 过后A前缀依旧显示在default前缀下边，当权重设置为98 ，upa reload过后A前缀正常显示在 default上边。

于是进行了第二次测试(**在经过第一次测试的基准上**) **order-desc为false时**，A前缀的权重为99，upa reload 过后无法完成升序排列，即A前缀显示在default前缀上边，于是将A前缀的权重分别修改为 98 97 96且进行upa reload，依旧显示在default上边，order-desc功能疑似不正常。

以上操作**除重启服务端**均按照upa reload后重新进入服务器进行测试

**Comment by CarmJos** [comment]
在我百思不得其解四处检查代码后，终于发现了问题所在：

`/upa reload` 指令不会影响现有玩家的权重内容，只会再次唤起“前缀检查”。因此，需要全部玩家重新进入游戏或服务器重启才会对权重进行生效。

我尝试在后续版本中针对全部玩家的前缀进行强制刷新。

**Comment by CarmJos** [comment]
您好，相关问题已定位。请下载 [runs@1905822777](https://github.com/CarmJos/UserPrefix/actions/runs/1905822777) 中的构建并安装，帮助我进行测试，谢谢！

**Comment by zhangnelson** [comment]
现/upa reload 指令可以强制刷新权重了，但无论order-desc设置为true 还是 false ，显示结果都为 权重高的显示在最上方，即权重高→权重低(降序排列)

**Comment by CarmJos** [comment]
您好，相关问题已定位，请下载 [runs@1906382882](https://github.com/CarmJos/UserPrefix/actions/runs/1906382882) 中的构建并安装，帮助我进行测试，谢谢！
