### ISSUE TITLE
重载 & 选取称号 出现报错, 正常执行

### ISSUE THREAD

**Issue by Yurinann** [CarmJos/UserPrefix#2]
服务器环境: 1.16.5 purpur (latest version), java 16.0.2
插件版本: 2.1.0, 最新

**重载:**
报错信息: https://paste.dismail.de/?901ab2b7b5d5e64e#31nau1YnB4p2cHq79KYVj5b9iJAwZrimqkptx4Bi3iCU

复现操作:
1. /userprefixadmin reload
2. 出现报错, 但能成功重载称号部分, 不影响主要功能使用

**称号选取切换:**
报错信息: https://paste.dismail.de/?d0c4c31e3b5f14dc#Ff8cbXW45BodQc4CUQoLrZcbR53RYK6yzv1iyqtY4EpL

复现操作:
1. /prefix (打开菜单)
2. 点击选取任意称号
3. 出现报错, 但能成功选取

期待修复报错, 十分感谢.

**Comment by CarmJos** [comment]
您好！

是不是前一份配置文件没启用“NAMEPREFIX"功能，随后启用再重载的呀？

**Comment by CarmJos** [comment]
还是说没有开启“namePrefix”功能，然后会报错呢？

**Comment by Yurinann** [comment]
您好！
之前开启过了这个功能，现在移交至其它系统进行处理，关闭后重载，与您问题的原理应该差异不大。
现在配置文件内 OnNamePrefix 为 false。

刚刚尝试了重新生成配置文件，使用 /upa reload 仍然存在报错。

**Comment by CarmJos** [comment]
2.2.1版本将修复，请稍候3分钟~

**Comment by Yurinann** [comment]
好的，感谢修复

更正：当 OnNamePrefix 为 true 时，返回正常的重载成功提示

**Comment by CarmJos** [comment]
请下载 2.1.1 版本，进行测试~

若问题解决，请回复已解决，我将关闭本issue。

感谢您提供详细的问题描述与及时的回复！

**Comment by Yurinann** [comment]
issue 原问题已解决，感谢您的修复！

---

出现了两个问题：
1. 当 OnNamePrefix 为 true 时，玩家加入事件报错：
https://paste.dismail.de/?6efdfc7300bf2366#5VpWQK4kg8gAtpWHhnRdrGHSZDSq93TkFtgygwN8eQgk

2. 当 OnNamePrefix 由 false 切换为 true 时重载，后台报错：
https://paste.dismail.de/?ba796b9054874681#6JwdZk3FEUfDeJXRLtKTxcbu8zWpb22c3K2Ab8eZgNra

**Comment by CarmJos** [comment]
新问题已修复，请下载 [2.1.2版本](https://github.com/CarmJos/UserPrefix/releases/tag/2.1.2) ~

感谢您提供详细的问题描述与及时的回复！

**Comment by Yurinann** [comment]
问题已解决，感谢您的及时修复！
