### ISSUE TITLE
feat(cmd): 使用命令创建称号

### ISSUE THREAD

**Issue by usernameOHH** [CarmJos/UserPrefix#29]
### **功能简述**
使用命令即可创建称号
比如这样：
/userprefix setup

请输入称号唯一标识
/userprefix setup test

请输入称号名字
/userprefix setup 测试

请输入称号内容
/userprefix setup 测试称号

请输入该称号的权重
/userprefix setup 1

请输入该称号检测的权限
/userprefix setup test.test1

该称号的GUI中使用的物品
/userprefix setup stone

是否在yml中添加注释
/userprefix setup true

这个称号的yml的文件名
/userprefix setup test.yml

### **需求来源**
老上后台感觉有点傻

### **功能参考**(可选)
-

### **附加内容**
-

**Comment by CarmJos** [comment]
鉴于目前需要配置的项目较多，该功能**可能**会在后续的更新中支持哦~

**Comment by CarmJos** [comment]
link #27

**Comment by CarmJos** [comment]
抱歉，经过综合考虑，该功能暂时放弃支持，感谢您的建议。
