### ISSUE TITLE
玩家自定义称号

### ISSUE THREAD

**Issue by usernameOHH** [CarmJos/UserPrefix#30]
### **功能简述**
有权限的玩家可以使用自定义称号
比如拥有 userprefix.test.1 权限的玩家可以设置一次，支持 & 改颜色
userprefix.test.2 可以设置两次
提供papi变量查看可以设置的数量 默认 0

### **需求来源**
想要自定义称号

### **功能参考**(可选)
-

### **附加内容**
-

**Comment by CarmJos** [comment]
您好，该功能应该不会做支持哦~
