### ISSUE TITLE
隐藏某个称号

### ISSUE THREAD

**Issue by usernameOHH** [CarmJos/UserPrefix#34]
### **功能简述**
如标题，隐藏某个称号，可以通过命令佩戴，op可以强制玩家佩戴称号（即使没有权限）

### **需求来源**
玩家私人称号

### **功能参考**(可选)
-

### **附加内容**
-

**Comment by CarmJos** [comment]
该功能应该不会被支持哦~ 现有权限极度依赖权限判断哦~
