### ISSUE TITLE
feat(cmd): 使用命令为玩家更换称号

### ISSUE THREAD

**Issue by usernameOHH** [CarmJos/UserPrefix#35]
### **功能简述**
使用命令为玩家更换称号

### **需求来源**
更方便和菜单插件搭配起来

### **功能参考**(可选)
-

### **附加内容**
-

**Comment by CarmJos** [comment]
您好，请帮助下载 [最新构件](https://github.com/CarmJos/UserPrefix/actions/runs/3165633085) 帮助测试本功能。 建议删除 `messages.yml` 中 `usage.admin` 部分以便重新生成帮助内容。

**Comment by CarmJos** [comment]
本次新增的指令为 `/upa set <玩家ID> <前缀ID>` 。

**Comment by usernameOHH** [comment]
嗯？更新了？太棒了

**Comment by usernameOHH** [comment]
已经测试可用

**Comment by CarmJos** [comment]
您好，已发版 [3.0.3](https://github.com/CarmJos/UserPrefix/releases/tag/3.0.3) 。

**Comment by usernameOHH** [comment]
好耶
那别的几个issues咋说捏

**Comment by CarmJos** [comment]
> 
有时间的话会去处理的哦。
