### ISSUE TITLE
papi reload之后变量不显示

### ISSUE THREAD

**Issue by usernameOHH** [CarmJos/UserPrefix#36]
### **问题简述**
在执行 /papi reload 之后 UserPrefix 的变量变成 %UserPrefix_prefix%
执行 /papi parse XYZ_2022 %UserPrefix_prefix% 输出结果为 %UserPrefix_prefix%
聊天栏和后台无报错，以及，我不确定是不是我的问题，但是先交个issues吧

**Comment by CarmJos** [comment]
UserPrefix采用的是 [插件内注册](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/PlaceholderExpansion#register-the-expansion) 注册的方式实现的变量功能，而PlaceholderAPI在reload的时候并不会重新加载已注册的插件内部变量，也不会唤起某个事件告知其他插件重新加载自己的变量。

部分在PlaceholderAPI重载后变量功能仍然可用的插件(如 LuckPerms)采用 [独立变量解释器](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/PlaceholderExpansion#with-a-plugin-external-jar) 的方式实现，该解释器由PlaceholderAPI自行管理(eCloud)，因此在重载时会被一同重新加载。

综上，您的问题暂时没有办法被优雅的解决。现存的解决方案是我去监听 `/papi reload` 等指令并重新注册，但总归不是完美的解决方案。
