### ISSUE TITLE
1.18默认生成参数报错

### ISSUE THREAD

**Issue by Coquettishpig** [CarmJos/UserPrefix#38]
![TQHG4`KYX%I`F`4A8T_61_U](https://user-images.githubusercontent.com/107100449/205444398-3958e0f8-8f9f-4649-825e-7dc7c23c7488.png)

**Comment by CarmJos** [comment]
您好，基础示例配置文件基于MineCraft 1.8 版本制作。如有其他需求，请自行修改配置以适配更新版本。

**Comment by CarmJos** [comment]
详见项目基础文档。
![image](https://user-images.githubusercontent.com/36306882/205490127-2a1a2a41-1cad-4446-ba53-167ade031977.png)
