### ISSUE TITLE
请更新一下spigot，那个网站上的插件还停留在2.4.2版本。

### ISSUE THREAD

**Issue by WitheredWinter** [CarmJos/UserPrefix#43]
### **功能简述**
请更新一下spigot，那个网站上的插件还停留在2.4.2版本。
请更新一下spigot，那个网站上的插件还停留在2.4.2版本。
请更新一下spigot，那个网站上的插件还停留在2.4.2版本。
### **需求来源**
这是一个非常好的插件，但spigot上一直不更新会让很多人望而却步不敢下载使用

**Comment by CarmJos** [comment]
抱歉，先前忙于事务忘记更新到SpigotMC上了。

![image](https://user-images.githubusercontent.com/36306882/215757304-5bc21403-e2cc-482f-a71f-59fdf13aac00.png)

目前已经更新，感谢您的提醒。如果更新内容中有需要改进的地方，也期待您能够指出我的错误。
