### ISSUE TITLE
feat(gui): 更多的GUI选项以及自定义GUI界面

### ISSUE THREAD

**Issue by RAURORA2** [CarmJos/UserPrefix#44]
### **功能简述**

比如可以加入一个按钮用来跳转到称号商店（既然都有back了那为啥不能有个shop）
然后在箱子菜单边缘的留白处可以自定义玻璃板之类的，格式我都写好了
### **需求来源**

肯定要啊
### **功能参考**(可选)

    tagshop:
      type: creeper_head
      name: '&e&l称号商店'
      lore:
      - ' '
      - '&f点击打开称号商店, 获取更多称号'
      slot: 45
      actions:
      - '[CONSOLE] trmenu open tagshop %player_name%'
    edge:
      type: glass_pane
      name: ' '
      slot: 0,9,18,27,36,45,54.....

**Comment by CarmJos** [comment]
您好，该功能已完成。需要拜托您下载 [此流水线对应成品构件](https://github.com/CarmJos/UserPrefix/actions/runs/4253604577) 并测试相关功能是否运行如您所愿。注意提前备份现有配置文件内容，强烈建议您重新生成新 `config.yml` 文件。

**Comment by CarmJos** [comment]
您可以 [点击这里](https://github.com/CarmJos/UserPrefix/suites/11161076103/artifacts/569779000) 下载对应构件。

**Comment by RAURORA2** [comment]
测试下来基本没问题，但是有如下几点:
1、slot项不支持多项数据以完成克隆式的排列
2、没有注明设置图标物品数量的选项（也可能是没有这个功能）
3、新发现的问题：当default-prefix: actions: 留空时，会执行一个默认的指令[console]say %player_name%选择了默认前缀，而不是什么都不执行（如果是设计成这样的希望能标注一下）

**Comment by CarmJos** [comment]
对于问题1，您可以使用

**Comment by CarmJos** [comment]
您好，对于问题1，您可以使用一下格式规定单个物品所在的多个格子：
```yaml
items:
  example:
    type: "STONE"
    name: "example"
    slots:
      - 1
      - 2
      - 3
      - 4
```

对于问题2，由于UserPrefix的重点并非GUI配置，因此暂不支持(也可能不会支持)数量选项。

对于问题3，我不清楚您的意思，建议您粘贴您自己的配置文件，以便我参考分析。

**Comment by RAURORA2** [comment]
> 您好，对于问题1，您可以使用一下格式规定单个物品所在的多个格子：
> 
> ```yaml
> items:
>   example:
>     type: "STONE"
>     name: "example"
>     slots:
>       - 1
>       - 2
>       - 3
>       - 4
> ```
> 
> 对于问题2，由于UserPrefix的重点并非GUI配置，因此暂不支持(也可能不会支持)数量选项。
> 
> 对于问题3，我不清楚您的意思，建议您粘贴您自己的配置文件，以便我参考分析。不过您可以先尝试使用以下格式，以规避默认值更新：`actions: []` 。

对于问题3，就是选择默认称号后执行的动作，如果直接留空不像你这样写个[]（当然我也不知道有这个括号是否可行），就会执行他自带的“[console]say %player_name%选择了默认前缀”，而不是什么都不执行，大概就是这个意思。不过照我认为括号应该是可行的吧，但是在别的称号文件里，如果留空则是什么都不执行，不需要额外添加括号。

**Comment by RAURORA2** [comment]
> 您好，对于问题1，您可以使用一下格式规定单个物品所在的多个格子：
> 
> ```yaml
> items:
>   example:
>     type: "STONE"
>     name: "example"
>     slots:
>       - 1
>       - 2
>       - 3
>       - 4
> ```
> 
> 对于问题2，由于UserPrefix的重点并非GUI配置，因此暂不支持(也可能不会支持)数量选项。
> 
> 对于问题3，我不清楚您的意思，建议您粘贴您自己的配置文件，以便我参考分析。不过您可以先尝试使用以下格式，以规避默认值更新：`actions: []` 。

不过我希望这个actions里能写个refresh来刷新整一个的界面而不是直接关闭界面，不过我用"[chat]userprefix"似乎也能同样达到这个效果。这个建议不采纳也没事。

**Comment by CarmJos** [comment]
好的，稍后我将正式发版，感谢您的建议。
