### ISSUE TITLE
MiniMessage语法支持

### ISSUE THREAD

**Issue by YuanYuanOwO** [CarmJos/UserPrefix#50]
### **功能简述**

想要支持 MiniMessage 语法，因为很简便，而且还有个很酷的预览器 https://webui.advntr.dev/
### **需求来源**

弄RGB更简便了，直接`<rainbow>`就好了，而且相对来说 MiniMessage 可能更简洁(?)
### **附加内容**

要是工作量很大就算了...

**Comment by CarmJos** [comment]
这个小插件我觉得不值得再绑个库，现在不是支持RGB和渐变了嘛(

**Comment by YuanYuanOwO** [comment]
> 这个小插件我觉得不值得再绑个库，现在不是支持RGB和渐变了嘛(

主要渐变写起来容易给脑子干宕机，可能大概就是图个`<rainbow>`（
或者说有什么其它好预览的方法嘛，跟MiniMessage预览器一样的

**Comment by CarmJos** [comment]
> > 这个小插件我觉得不值得再绑个库，现在不是支持RGB和渐变了嘛(
> 
> 主要渐变写起来容易给脑子干宕机，可能大概就是图个`<rainbow>`（ 或者说有什么其它好预览的方法嘛，跟MiniMessage预览器一样的

啊嘞，可是这个是前缀啊，前缀发出来消息不是不会变吗(?

UserPrefix已经支持渐变了呀， &<#XXXXXX>内容&<#XXXXXX>
