### ISSUE TITLE
1.21.1配置读取出现NETHER_PORTAL

### ISSUE THREAD

**Issue by MingGRE** [CarmJos/UserPrefix#51]
### **问题简述**
1.21.1跑本插件配置读取异常，出现`NETHER_PORTAL`

### **问题截图**
![image](https://github.com/user-attachments/assets/17206a1e-8a34-4bb4-b6c2-9aa19b882e18)

### **操作环境**
OS: Windows 10 Workstation 22h2
Java：JDK-22

**Comment by Shadow403** [comment]
![image](https://github.com/user-attachments/assets/d7704993-217e-4820-9e8a-d726b4946969)

错误一致

**Comment by CarmJos** [comment]
您好，请下载 [此构件](https://github.com/CarmJos/UserPrefix/actions/runs/9965068858) 以测试问题是否解决。
