### ISSUE TITLE
希望能加一个指令，用于玩家添加自定义前缀

### ISSUE THREAD

**Issue by Noogear** [CarmJos/UserPrefix#53]
### **功能简述**
玩家输入一个指令后，根据自定义前缀配置模板生成一个前缀
管理员可以添加通用配置模板，模板包括
1、前缀安装前、安装后的文字介绍
2、前缀长度
3、能否使用彩色、能否使用minimessage
4、玩家能否修改以及修改次数上限
5、称号能否分享以及使用人数上限（分享功能实现不了就算了）
6、有效期

### **需求来源**

来点新功能~~加点新血液！！！！！！！

### **附加内容**

操作步骤：
1、玩家被赋予自定义称号权限，该权限在创建完自定义称号后消失，权限可以通过数字的形式叠加
2、玩家输入/userprefix custom add {prefix} 创建称号，有权限的才能创建称号
3、首先会预览创建后的称号，并不会直接创建
4、输入/userprefix custom yes/no 对该称号进行确定和否决，确定会消耗创建次数，否则不会，系统提醒剩余次数
5、自定义称号优先级在所有称号之前，在称号仓库最前面，由不同的模板（管理员创建）体现出他是自定义称号，并且加入papi%prefix_custom%为ture false

**Comment by CarmJos** [comment]
考虑到目前配置的格式和情况，似乎并不太方便直接支持此功能。可以考虑基于UserPrefix的API额外开发插件来实现。

**Comment by RAURORA2** [comment]
> 考虑到目前配置的格式和情况，似乎并不太方便直接支持此功能。可以考虑基于UserPrefix的API额外开发插件来实现。

称号的位置用{0}等特征符号替代，称号长度和能否用彩色可以加入配置，然后有效期、次数上限可以用权限替代

**Comment by MineSunshineone** [comment]
感觉有这个功能就完美了

**Comment by CarmJos** [comment]
考虑到“自定义称号”本身就越过了“权限称号”的范畴，且数据结构与现有情况冲突，故此功能可能在一段时间内不会实现。
