### ISSUE TITLE
顏色漸變

### ISSUE THREAD

**Issue by LinAk900127** [CarmJos/UserPrefix#57]
### **功能简述**
完整 RGB 十六進制支持
自動漸層/彩虹格式

### **需求来源**
部分相似插件有這些功能，我希望UserPrefix也能擁有

### **功能参考**(可选)
DeluxeTags plugin

**Comment by CarmJos** [comment]
您好，目前已经支持此功能。

您可以使用 &<#xxxxxx> 来框选一部分文字，会从起始区域自动渐变到结束区域。

我稍后会将此功能添加到文档中，感谢您的关注和认可！

**Comment by CarmJos** [comment]
关于rgb支持，请见项目介绍文档里有写明。
