### ISSUE TITLE
[Bug] Prefix 显示不支持 RGB &(#xxxxxx) 设定

### ISSUE THREAD

**Issue by Yurinann** [CarmJos/UserPrefix#7]
**问题简述**
Prefix 显示不支持 RGB &(#xxxxxx) 设定

**问题来源**
1. 将默认称号 / 自定义称号 名称 (display-name) 设定为 &(#xxxxxx)名称
2. 打开菜单，切换称号时发现颜色不正常显示

**预期结果**(可选)
正常显示 RGB 内容（如选择称号后反馈 sendMessage 部分的 RGB 颜色即为正确读取效果）

**问题截图/问题报错**
```yaml
display-name: "&(#FFC75F)§l旅行者 前缀 §f(点击切换)"
```
![QQ截图20211230220857](https://user-images.githubusercontent.com/75569395/147759167-62059d05-2295-4755-aa93-c6ca20895894.png)

**操作环境**
- Paper-404 (MC: 1.17.1)
- UserPrefix 2.1.9

**其他补充**
希望同时可以支持 § -> & 自动转换。

**Comment by CarmJos** [comment]
这并不是Bug，而是UserPrefix采用了最原始的ItemStack序列化方法以支持全部可能的情况——当然或许并不是很只能。

我正准备在下个版本实现针对displayName与lor的颜色自动替换，并支持PlaceholderAPI的变量功能，最快今晚您就可以进行更新。

**Comment by Yurinann** [comment]
感谢您的及时回复与帮助，又从您这里学习到了一些东西，接下来我会更加严谨对待问题。

**Comment by CarmJos** [comment]
您好，请 [点击这里](https://github.com/CarmJos/UserPrefix/suites/4794184827/artifacts/134249840) 下载最新构建进行测试。如果功能正常且满足需要，请帮助提供几张效果图片与配置文件截图，便于我发布release，谢谢！

**Comment by Yurinann** [comment]
![QQ截图20211230234219](https://user-images.githubusercontent.com/75569395/147766448-4f1c2ea1-e6c3-4557-88c3-7b2b04462b8c.png)
![QQ截图20211230234238](https://user-images.githubusercontent.com/75569395/147766476-e832bb4e-0751-4540-95f3-05d072696fb1.png)

如果我的用法没有错误，看起来实现效果并不理想？
另：papi-player 拓展已安装。

**Comment by CarmJos** [comment]
检查了一下，原来是在做向下兼容时忘记应用新特性。

请 [点击这里](https://github.com/CarmJos/UserPrefix/suites/4794666167/artifacts/134280123) 下载最新构建进行测试。如果功能正常且满足需要，请帮助提供几张效果图片与配置文件截图，便于我发布release，谢谢！

**Comment by CarmJos** [comment]
另外，displayName中也是可以使用RGB颜色与PlaceholderAPI变量的。

**Comment by Yurinann** [comment]
![QQ截图20211231001841](https://user-images.githubusercontent.com/75569395/147769478-0ecc786e-7f24-48b7-b1e2-26461c761070.png)
![QQ截图20211231001903](https://user-images.githubusercontent.com/75569395/147769485-0b43f34f-d7ae-444b-bf6a-b702b6443bec.png)

已经成功实现，感谢您的帮助。如需要更多效果图片请说明，我会一一提供。

**Comment by CarmJos** [comment]
感谢您的建议与支持，新版本 [[v2.2.0]](https://github.com/CarmJos/UserPrefix/releases/tag/v2.2.0) 已发布。

**Comment by CarmJos** [comment]
我刚刚发布了新版本 [2.2.1](https://github.com/CarmJos/UserPrefix/releases/tag/v2.2.1) ,添加了统计数据功能,请问您愿意下载使用一下吗？

**Comment by Yurinann** [comment]
> 我刚刚发布了新版本 [2.2.1](https://github.com/CarmJos/UserPrefix/releases/tag/v2.2.1) ,添加了统计数据功能,请问您愿意下载使用一下吗？

当前已经使用，感谢。
